/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:a3920719-8eb8-4542-bbac-2f42cc21ac5a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_vehw4LN4M",
    "aws_user_pools_web_client_id": "711pkhklgj6no9omb0c2aotfaa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://l57zspplhfgjtc7mlo4x2hf5rq.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aa7hoct2ejhh5iebwf3qf67scm",
    "aws_user_files_s3_bucket": "bucket-for-notes-app124559-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
