/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:a3920719-8eb8-4542-bbac-2f42cc21ac5a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_vehw4LN4M",
    "aws_user_pools_web_client_id": "711pkhklgj6no9omb0c2aotfaa",
    "oauth": {}
};


export default awsmobile;
